### ISSUE TITLE
Building ScanTailor with mingw cmake error

### ISSUE THREAD

**Issue by mookdevelop** [4lex4/scantailor-libs-build#4]
C:\scantailor\sources\build>cmake -G "MinGW Makefiles" --build ..
-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
-- Check for working C compiler: C:/mingw64/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/mingw64/mingw64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/mingw64/mingw64/bin/g++.exe
-- Check for working CXX compiler: C:/mingw64/mingw64/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Boost (missing: unit_test_framework prg_exec_monitor) (found
  suitable version "1.70.0", minimum required is "1.60")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.15/Modules/FindBoost.cmake:2142 (find_package_handle_standard_args)
  CMakeLists.txt:276 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/scantailor/sources/build/CMakeFiles/CMakeOutput.log".

**Comment by 4lex4** [comment]
I've already made over the building system so this problem should go off. I'll upload that updated in a week or two.

**Comment by oreg-bandi** [comment]
I understood that this is issue is closed but it still pops up in my compilation. 
D:\work\4lex4\scantailor-advanced-master\build>cmake -G "MinGW Makefiles" --build ..
CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Boost (missing: unit_test_framework prg_exec_monitor) (found
  suitable version "1.65.1", minimum required is "1.60")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.15/Modules/FindBoost.cmake:2142 (find_package_handle_standard_args)
  CMakeLists.txt:192 (find_package)


-- Configuring incomplete, errors occurred!
See also "D:/work/4lex4/scantailor-advanced-master/build/CMakeFiles/CMakeOutput.log".

**Comment by 4lex4** [comment]
Download the latest version of boost.

**Comment by oreg-bandi** [comment]
Thanks for the hint but unfortunately does not work, Here is the log

D:\work\4lex4_\scantailor-advanced-master\build>cmake -G "MinGW Makefiles"
--build ..
CMake Error at
D:/work/4lex4_/libs/Boost/lib/cmake/Boost-1.73.0/BoostConfig.cmake:141
(find_package):
  Found package configuration file:


D:/work/4lex4_/libs/Boost/lib/cmake/boost_unit_test_framework-1.73.0/boost_unit_test_framework-config.cmake

  but it set boost_unit_test_framework_FOUND to FALSE so package
  "boost_unit_test_framework" is considered to be NOT FOUND.  Reason given
by
  package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_unit_test_framework-mgw8-mt-x64-1_73.a (mgw8,
  Boost_COMPILER=mgw81)

Call Stack (most recent call first):
  D:/work/4lex4_/libs/Boost/lib/cmake/Boost-1.73.0/BoostConfig.cmake:258
(boost_find_component)
  C:/Program Files/CMake/share/cmake-3.15/Modules/FindBoost.cmake:422
(find_package)
  CMakeLists.txt:192 (find_package)


-- Configuring incomplete, errors occurred!
See also
"D:/work/4lex4_/scantailor-advanced-master/build/CMakeFiles/CMakeOutput.log".
