### ISSUE TITLE
libtiff\tif_lzma.c:37:18: fatal error: lzma.h: No such file or directory

### ISSUE THREAD

**Issue by shirha** [4lex4/scantailor-libs-build#6]
I received fatal error trying to run mingw32-make -j. Do you have a suggestion I can try.

[mingw32-make.log](https://github.com/4lex4/scantailor-libs-build/files/4400680/mingw32-make.log)
[tiff410-dirlist.txt](https://github.com/4lex4/scantailor-libs-build/files/4400681/tiff410-dirlist.txt)

**Comment by 4lex4** [comment]
Update `scantailor-libs-build-master` (clone this project) and reconfigure tiff (launch `configure_libs_x<arch>.bat` script), then launch cmake and mingw32-make again.

**Comment by shirha** [comment]
That made it thru the dependency build but now I get an error during cmake for the ScanTailor build. 
Could you help me with this please?

[cmake2.log](https://github.com/4lex4/scantailor-libs-build/files/4424886/make2.log)
[CMakeOutput.log](https://github.com/4lex4/scantailor-libs-build/files/4424887/CMakeOutput.log)

**Comment by 4lex4** [comment]
If you want to build scantailor on msys2 environment with its own mingw you should follow Linux instructions not Windows. MinGW in msys is different from MinGW-w64 for Windows, the former implicitly uses msys dependecy and POSIX emulation layer which is slow, the latter uses Windows API directly.  
Just follow the instruction and install MinGW-w64 toolchain for Windows. In the instruction for Windows msys2 is used only to get the configuration files and not for building.

**Comment by shirha** [comment]
I install MinGW-64 as you asked but I still got the CMake error "missing: unit_test_framework prg_exec_monitor". Could you look at it one more time. I really need ScanTailor Advance because I'm working on a 1000 page scanned book. If you had a link to a Windows binary I would also use that. This is the first time I have ever tried to build a cpp program so I appreciate you patience. Thanks in advance for your assistance.

[cmake3.log](https://github.com/4lex4/scantailor-libs-build/files/4430771/cmake3.log)
[CMakeOutput.log](https://github.com/4lex4/scantailor-libs-build/files/4430775/CMakeOutput.log)

**Comment by 4lex4** [comment]
Why do you use the old version of boost? Remove both Boost and boost_* folders from the libs dir, download and unpack the latest version of boost there, navigate to libs\libs-build\build dir (via cd command) and input `mingw32-make -j%NUMBER_OF_PROCESSORS% Boost`

**Comment by shirha** [comment]
I upgraded to boost_1_72_0 and it built OK but when I ran "cmake -G "MinGW Makefiles" --build .." for scantailor-advanced-1.0.16 it complained about Qt

[cmake scantailor build.log](https://github.com/4lex4/scantailor-libs-build/files/4431973/cmake.scantailor.build.log)
[CMakeOutput.log](https://github.com/4lex4/scantailor-libs-build/files/4431980/CMakeOutput.log)

so I deleted the directories

libs\scantailor-libs-build-master\build
libs\Boost
libs\Qt
scantailor-advanced-1.0.16\build

and tried rebuilding the dependencies with the new compiler MinGW-w64 from "configure_libs_x64.bat" to see if that would fix it but Qt complained during "mingw32-make -j".

[make dep qt.log](https://github.com/4lex4/scantailor-libs-build/files/4431977/make.dep.qt.log)
[CMakeOutput.log](https://github.com/4lex4/scantailor-libs-build/files/4431976/CMakeOutput.log)

What am I doing wrong here?
Thanks

**Comment by 4lex4** [comment]
Your qt sources seem to be corrupted by previous wrong configuration with msys mingw. Remove everything from the libs folder, unpack all the sources and scantailor-libs-build-master again and start building from the beginning following the instruction step by step.

**Comment by shirha** [comment]
Success! Thank you so much for your help. It was certainly appreciated.
