### ISSUE TITLE
Cmake Error 

### ISSUE THREAD

**Issue by Ra-Na** [4lex4/scantailor-libs-build#8]
`-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   unit_test_framework
--   prg_exec_monitor
CMake Error at CMakeLists.txt:193 (add_compile_definitions):
  Unknown CMake command "add_compile_definitions".

-- Configuring incomplete, errors occurred!`

My setup:

Ubuntu 18.04
cmake version 3.10.2

Dependencies versions: `apt-cache showpkg gcc-7 g++-7 cmake libjpeg-dev libpng-dev libtiff5 libtiff5-dev libboost-test1.65-dev libboost-test1.65.1 qtbase5-dev libqt5svg5-dev qttools5-dev qttools5-dev-tools libqt5opengl5-dev libpthread-stubs0-dev | grep -B1 -A1 Versions` gives

Package: gcc-7
Versions: 
7.5.0-3ubuntu1~18.04 (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_bionic-updates_main_binary-amd64_Packages) (/var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_bionic-security_main_binary-amd64_Packages) (/var/lib/dpkg/status)

Package: g++-7
Versions: 
7.5.0-3ubuntu1~18.04 (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_bionic-updates_main_binary-amd64_Packages) (/var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_bionic-security_main_binary-amd64_Packages) (/var/lib/dpkg/status)

Package: cmake
Versions: 
3.10.2-1ubuntu2.18.04.1 (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_bionic-updates_main_binary-amd64_Packages) (/var/lib/dpkg/status)

Package: libjpeg-dev
Versions: 
8c-2ubuntu8 (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_bionic_main_binary-amd64_Packages) (/var/lib/dpkg/status)

Package: libpng-dev
Versions: 
1.6.34-1ubuntu0.18.04.2 (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_bionic-updates_main_binary-amd64_Packages) (/var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_bionic-security_main_binary-amd64_Packages) (/var/lib/dpkg/status)

Package: libtiff5
Versions: 
4.0.9-5ubuntu0.3 (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_bionic-updates_main_binary-amd64_Packages) (/var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_bionic-security_main_binary-amd64_Packages) (/var/lib/dpkg/status)

Package: libtiff5-dev
Versions: 
4.0.9-5ubuntu0.3 (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_bionic-updates_main_binary-amd64_Packages) (/var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_bionic-security_main_binary-amd64_Packages) (/var/lib/dpkg/status)

Package: libboost-test1.65-dev
Versions: 
1.65.1+dfsg-0ubuntu5 (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_bionic_universe_binary-amd64_Packages) (/var/lib/dpkg/status)

Package: libboost-test1.65.1
Versions: 
1.65.1+dfsg-0ubuntu5 (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_bionic_universe_binary-amd64_Packages) (/var/lib/dpkg/status)

Package: qtbase5-dev
Versions: 
5.9.5+dfsg-0ubuntu2.5 (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_bionic-updates_main_binary-amd64_Packages) (/var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_bionic-security_main_binary-amd64_Packages) (/var/lib/dpkg/status)

Package: libqt5svg5-dev
Versions: 
5.9.5-0ubuntu1 (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_bionic_main_binary-amd64_Packages) (/var/lib/dpkg/status)

Package: qttools5-dev
Versions: 
5.9.5-0ubuntu1 (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_bionic_universe_binary-amd64_Packages) (/var/lib/dpkg/status)

Package: qttools5-dev-tools
Versions: 
5.9.5-0ubuntu1 (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_bionic_universe_binary-amd64_Packages) (/var/lib/dpkg/status)

Package: libqt5opengl5-dev
Versions: 
5.9.5+dfsg-0ubuntu2.5 (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_bionic-updates_main_binary-amd64_Packages) (/var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_bionic-security_main_binary-amd64_Packages) (/var/lib/dpkg/status)

Package: libpthread-stubs0-dev
Versions: 
0.3-4 (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_bionic_main_binary-amd64_Packages) (/var/lib/dpkg/status)

**Comment by 4lex4** [comment]
Are you trying to build an old version of scantailor? Clone master branch and build that. CMake 3.10 is bugged and can't find jpeg, so you need to update that anyway (see #7).
